# by F.C.
#
# Configuration file for media-sound/piper (see my local repo). ONNX models
# are in /usr/local/share/piper-tts/ (currently only it-IT, en-US, en-GB).
#
# CONFIGURATION BELOW IS ONLY FOR 22050 RATE CONVERSION (medium models, see
# the related model .json file). See https://github.com/OHF-voice/piper1-gpl
#
# USE PIPEWIRE AS OUTPUT CHANNEL (pw-play).
#
# After changes type from user: systemctl restart --user speech-dispatcher.socket
#
# Useful references:
# https://build.opensuse.org/projects/home:dheidler/packages/piper-tts/files/speech-dispatcher.conf


# Debug turns debugging on or off
# See speechd.conf for information where debugging information is stored
Debug 0

# GenericExecuteSynth is the shell command that should be
# executed in order to say some message. This command must
# stop saying the message on SIGKILL, otherwise it's useless.
# Use a wrapper to automatically set sampling rate and volume.
GenericExecuteSynth "/usr/local/share/piper-tts/piper-wrapper \"$DATA\" $LANGUAGE $VOICE $VOLUME"

GenericCmdDependency "piper"
GenericCmdDependency "pw-play"
GenericSoundIconFolder "/usr/share/sounds/sound-icons/"

GenericDefaultCharset "utf-8"

GenericLanguage "en"    "en-us" "utf-8"
GenericLanguage "en-us" "en-us" "utf-8"
GenericLanguage "en-gb" "en-gb" "utf-8"
GenericLanguage "it"    "it"    "utf-8"

# AddVoice specifies which $VOICE string should be assigned
# to each language and symbolic voice name. All the voices
# you want to use must be specified here.
#
# NOTE: HERE THE LANGUAGE CODES MUST BE ALL IN MINUSCOLE!

AddVoice "en"     "MALE1"    "en_US-mike-medium"
AddVoice "en"     "FEMALE1"  "en_US-ljspeech-medium"

AddVoice "en-us"  "MALE1"    "en_US-mike-medium"
AddVoice "en-us"  "FEMALE1"  "en_US-ljspeech-medium"

AddVoice "en-gb"  "MALE1"    "en_GB-alan-medium"
AddVoice "en-gb"  "FEMALE1"  "en_GB-alba-medium"

AddVoice "it"     "MALE1"    "it_IT-riccardo-x_low"
AddVoice "it"     "FEMALE1"  "it_IT-paola-medium"

# DefaultVoice specifies which $VOICE string should be
# used if no voice is specified otherwise.

DefaultVoice "en_US-mike-medium"
