# By F.C.
#
# Enable the "Fn3" button as "scroll button" on the ELECOM HUGE TrackBall in KDE Plasma, and
# also remap the "Fn1" button to act like the "middle button" (i.e. the button under the wheel).
# This works only under X11; for Wayland see the user's script "enable_trackbal_scroll_button.sh".
#
# The KDE settings "Mouse and Touchpad" -> "Mouse" -> "Hold down middle button and move mouse to scroll" must
# be enabled (otherwise Fn3 is ignored). Despite the warning, such settings will not interfere with the trackball
# middle button's normal function (because the scroll button is overridden and is not the middle button anymore).
#
# See also the ebuild "games-util/input-remapper" in GURU overlay (it works for both X11 and Wayland).

Section "InputClass"
	Identifier "ELECOM TrackBall Mouse HUGE TrackBall"
	MatchProduct "ELECOM TrackBall Mouse HUGE TrackBall"
	MatchIsPointer "on"
	Driver "libinput"
	Option "ButtonMapping" "1 2 3 4 5 6 7 8 9 2 11 12"
	Option "ScrollMethod" "Button"
	Option "ScrollButton" "12"
EndSection
