# by F.C.
#
# Use custom signing key for kernel modules. ENSURE
# THE KEY IS PROTECTED (see /etc/kernel/certs/README).
MODULES_SIGN_KEY="/etc/kernel/certs/signing_key.pem"
MODULES_SIGN_CERT="/etc/kernel/certs/signing_key.pem"
MODULES_SIGN_HASH="sha512"
